# Lecture 2 #

We are implementing the sieve of Eratosthenes below. This algorithm for finding lists of prime numbers has been around for a while. https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes

This algorithm is very fast. Using $10^8$ as an input will give you all primes less than $100$ million. If you had this list in the 70s, you would know more prime numbers than all of humanity combined.

In [3]:
import numpy as np
def sieve(n):
    '''This function returns all the primes below n as an array using the Sieve of Eratosthenes.'''
    import numpy as np
    #Create an array of 1s
    A=np.ones((n,), dtype = bool)
    #This tells us the values we search through. We are using the Sieve Eratosthenes
    for i in range(2, int(n**0.5+1)):
        if (A[i]):
            #Check every i values starting at i**2
            A[i*i::i] = False
    
    #Takes the indices with non-zero values and removes 0 and 1 from it
    primes = np.delete(np.nonzero(A),[0,1],1)
    return primes[0]

primes = sieve(10**8)

#Printing the array directly isn't very helpful
print(primes)

#Instead, we can check if individual numbers are in the array 
print(71 in primes)

[       2        3        5 ... 99999959 99999971 99999989]
True


In [14]:
#We specifically use dtype = bool, as we only care if each number is crossed out in the sieve at each step
A=np.ones((20,), dtype = bool)

A[3] = 0
A[5] = 0
print(A)
#This returns the array consisting of the indices of the non-zero values
print(np.nonzero(A))
#Here, we delete the 0th and 1st entries of the non-zero array. We need to use delete, since we are working with arrays
print(np.delete(np.nonzero(A),[0,1],1))

[ True  True  True False  True False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
(array([ 0,  1,  2,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19]),)
[[ 2  4  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]


## Exercise 1 ##
A positive integer is a prime permutation if every permutation of the digits is also prime. All $1$ digit primes are prime permutations. Another example is $17$ (as $71$ is also prime).

How many positive integer are prime permutations and less than $1000$? (Note positive integers cannot start with $0$).

In [5]:
#This is much nicer with itertools
n = 1000
primes = sieve(n)
import itertools as it

#These are the permutation primes
perms = []
for i in primes:
    
    #We convert to a string for easy use of itertools
    num = str(i)
    
    #This is the generator we can use as an iterable when making our checks
    checks = it.permutations(num)
    
    is_perm = True
    
    #If any check is not a prime, then we break the inner loop and do not append i
    for check in checks:
        if not int(''.join(check)) in primes:
            is_perm = False
            break
    
    if is_perm:
        perms.append(i)

print(perms)
print(len(perms))

[2, 3, 5, 7, 11, 13, 17, 31, 37, 71, 73, 79, 97, 113, 131, 199, 311, 337, 373, 733, 919, 991]
22


In [12]:
import itertools as it

#Permutations care about orderings of the elements. Default is permutations of all elements
perms = it.permutations('abc')
print('Permutations')
#We join the tuples into strings using the join function method
for perm in perms:
    print(''.join(perm))
    
print("\nCombinations")
#Combinations do not care about the order of the elements. Here we check all combinations of 2 elements
combs = it.combinations('abc',r=2)
for comb in combs:
    print(''.join(comb))

Permutations
abc
acb
bac
bca
cab
cba

Combinations
ab
ac
bc


## More with Itertools ##

In [13]:
#Permutations can be done by taking all 2 element permutations of the iterable, as done below
twodigits = it.permutations('abc',r=2)

for i in twodigits:
    print(i)

('a', 'b')
('a', 'c')
('b', 'a')
('b', 'c')
('c', 'a')
('c', 'b')
